export const CRITERIA_LIBRARY = {
  homepage: [
    {
      id: "homepage-001",
      category: "content-hierarchy",
      rule: "Value proposition clear within 5 seconds",
      guidance: "Visitors should understand what the site offers, for whom, and why it matters without scrolling or reading multiple sections.",
      source: "Nielsen Norman Group — research on above-the-fold attention and first impressions",
    },
    {
      id: "homepage-002",
      category: "cta-effectiveness",
      rule: "Single, high-contrast dominant call-to-action above the fold",
      guidance: "One clear next step should stand out, not several competing buttons of similar visual weight.",
      source: "Widely cited CRO research (CXL, Unbounce) on single-CTA pages outperforming multi-CTA pages",
    },
    {
      id: "homepage-003",
      category: "content-hierarchy",
      rule: "F-pattern or Z-pattern visual hierarchy",
      guidance: "Key content should follow natural eye-tracking scan patterns rather than fighting against them.",
      source: "Nielsen Norman Group — \"F-Shaped Pattern For Reading Web Content\" eye-tracking studies",
    },
    {
      id: "homepage-004",
      category: "navigation",
      rule: "Navigation limited to a manageable number of top-level items",
      guidance: "Fewer choices reduce decision time and cognitive load for a first-time visitor.",
      source: "Hick's Law (Hick, 1952; Hyman, 1953) — decision time increases with number of choices",
    },
    {
      id: "homepage-005",
      category: "trust-credibility",
      rule: "Trust signals visible without scrolling (reviews, security badges, recognizable customer logos)",
      guidance: "Visitors form trust judgments very quickly; signals need to be immediately visible, not buried below the fold.",
      source: "Baymard Institute's publicly available articles on trust signal placement",
    },
    {
      id: "homepage-006",
      category: "accessibility",
      rule: "Mobile tap targets at least 44x44px",
      guidance: "Small tap targets cause mis-taps and frustration, especially in the primary navigation and CTA.",
      source: "Apple Human Interface Guidelines / Google Material Design accessibility guidance",
    },
    {
      id: "homepage-007",
      category: "performance",
      rule: "Largest Contentful Paint under approximately 2.5 seconds",
      guidance: "Slow-loading hero content directly correlates with higher bounce rates before a visitor sees any value proposition.",
      source: "Google Core Web Vitals research correlating LCP with bounce and conversion rate",
    },
    {
      id: "homepage-008",
      category: "ux-friction",
      rule: "No more than one primary decision presented at a time above the fold",
      guidance: "Too many simultaneous options increase abandonment through choice overload.",
      source: "Iyengar & Lepper (2000), \"When Choice is Demotivating\" — widely cited choice-overload research",
    },
    {
      id: "homepage-009",
      category: "accessibility",
      rule: "Body text meets WCAG AA contrast ratio (4.5:1 minimum)",
      guidance: "Low-contrast text reduces readability for all users and excludes visually impaired visitors entirely.",
      source: "WCAG 2.1 Success Criterion 1.4.3 (Contrast Minimum)",
    },
    {
      id: "homepage-010",
      category: "visual-friction",
      rule: "Consistent visual language across sections (spacing, type, color use)",
      guidance: "Inconsistency increases cognitive load and undermines perceived credibility, even when each section looks fine in isolation.",
      source: "Nielsen's 10 Usability Heuristics — Consistency and Standards",
    },
  ],
  checkout: [
    {
      id: "checkout-001",
      category: "form-friction",
      rule: "Guest checkout available (no forced account creation)",
      guidance: "Forcing account creation before purchase is one of the most consistently cited reasons for cart abandonment.",
      source: "Baymard Institute's publicly published checkout usability research",
    },
    {
      id: "checkout-002",
      category: "checkout-friction",
      rule: "Total cost including shipping and taxes shown before the final step",
      guidance: "Unexpected costs revealed late in checkout are consistently the top-cited reason for cart abandonment.",
      source: "Baymard Institute's publicly cited cart abandonment survey data (\"extra costs too high\" as a leading reason)",
    },
    {
      id: "checkout-003",
      category: "form-friction",
      rule: "Visible progress indicator across checkout steps",
      guidance: "Users should always be able to see where they are in a multi-step process and how much remains.",
      source: "Nielsen's 10 Usability Heuristics — Visibility of System Status",
    },
    {
      id: "checkout-004",
      category: "form-friction",
      rule: "Minimal form fields with inline validation",
      guidance: "Every additional field reduces completion rate; errors should be caught immediately, not after submission.",
      source: "Luke Wroblewski, \"Web Form Design: Filling in the Blanks\" — widely cited form-optimization research",
    },
    {
      id: "checkout-005",
      category: "checkout-friction",
      rule: "Multiple payment methods available (card, digital wallets, etc.)",
      guidance: "Limited payment options exclude users who don't have or don't want to use the sole available method.",
      source: "Baymard Institute's publicly cited research on payment method availability and checkout completion",
    },
    {
      id: "checkout-006",
      category: "form-friction",
      rule: "Clear, specific, non-technical error messages",
      guidance: "Generic or technical errors leave users unable to self-correct and often cause outright abandonment.",
      source: "Nielsen's 10 Usability Heuristics — Help Users Recognize, Diagnose, and Recover from Errors",
    },
    {
      id: "checkout-007",
      category: "trust-credibility",
      rule: "Security or trust badges near payment fields",
      guidance: "Visible reassurance at the moment of highest anxiety — entering payment details — measurably reduces abandonment.",
      source: "Established e-commerce trust research widely cited in CRO literature on trust-signal placement near sensitive form fields",
    },
    {
      id: "checkout-008",
      category: "checkout-friction",
      rule: "Cart remains editable from within checkout (no dead-end flow)",
      guidance: "Users need to correct quantities or remove items without restarting the entire checkout process.",
      source: "Nielsen's 10 Usability Heuristics — User Control and Freedom",
    },
    {
      id: "checkout-009",
      category: "performance",
      rule: "Checkout pages load quickly with no blocking scripts",
      guidance: "Performance issues at the checkout stage have an outsized impact on abandonment compared to other pages.",
      source: "Google Core Web Vitals research; checkout-stage performance sensitivity widely cited in e-commerce CRO literature",
    },
    {
      id: "checkout-010",
      category: "visual-friction",
      rule: "No unexpected interstitials or upsell interruptions during checkout",
      guidance: "Any interruption at this stage introduces a new decision point where the user can abandon the purchase entirely.",
      source: "General friction-reduction principle widely applied in checkout UX research",
    },
  ],
};
